# See https://grafana.com/docs/grafana/latest/installation/docker/

version: "3"

services:
  grafana:
    image: grafana/grafana-oss:9.2.1
    container_name: grafana
    volumes:
      - /volume2/docker/grafana/var/lib/grafana:/var/lib/grafana
    restart: always
    user: "0"
    ports:
      - 3010:3000
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_ANALYTICS_CHECK_FOR_UPDATES=true
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=true
      - GF_INSTALL_PLUGINS=briangann-gauge-panel,fetzerch-sunandmoon-datasource,flant-statusmap-panel,dalvany-image-panel,grafana-worldmap-panel
