# See https://hub.docker.com/_/influxdb

version: "3"

services:
  influxdb:
    image: influxdb::2.4
    container_name: influxdb
    volumes:
      - /volume2/docker/influxdb/etc/influxdb2:/etc/influxdb2
      - /volume2/docker/influxdb/var/lib/influxdb2:/var/lib/influxdb2
    restart: always
    ports:
      - 8086:8086/tcp
      - 2003:2003/tcp
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME="<MY_USERNAME>"
      - DOCKER_INFLUXDB_INIT_PASSWORD="<MY_PASSWORD>"
      - DOCKER_INFLUXDB_INIT_ORG="<MY_ORG>"
      - DOCKER_INFLUXDB_INIT_BUCKET="<MY_INIT_BUCKET>"
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="<MY_TOKEN>"

  telegraf:
    image: telegraf:1.24
    container_name: telegraf
    restart: always
    links:
      - influxdb
    volumes:
      - /volume2/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=<MY_USERNAME>
      - DOCKER_INFLUXDB_INIT_PASSWORD=<MY_PASSWORD>
      - DOCKER_INFLUXDB_INIT_ORG=<MY_ORG>
      - DOCKER_INFLUXDB_INIT_BUCKET=<MY_INIT_BUCKET>
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="<MY_TOKEN>"
      - INFLUX_TOKEN="<MY_TOKEN>"
      - INFLUX_ORG="Casa"
      - INFLUX_BUCKET=<MY_INIT_BUCKET>
      - INFLUX_HOST="http://<MY_IP_ADDRESS>:8086"
