# See https://github.com/geerlingguy/internet-pi

version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: 1026:1026
    links:
      - alertmanager
      - node-exporter
      - ping:ping
      - speedtest:speedtest
    ports:
      - 9090:9090
    volumes:
      - /volume2/docker/prometheus/configs:/etc/prometheus
      - /volume2/docker/prometheus/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  ping:
    tty: true
    stdin_open: true
    expose:
      - 9115
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    restart: always
    volumes:
      - /volume2/docker/blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'

  speedtest:
    expose:
      - 9798
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    user: 1026:1026
    ports:
      - 9093:9093
    volumes:
      - /volume2/docker/prometheus/data/alertmanager:/alertmanager

  node-exporter:
    privileged: true
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume2)($$|/)"
 